### ISSUE TITLE
pfsense 2.7 error after upgrade

### ISSUE THREAD

**Issue by jcattan** [rbicelli/pfsense-zabbix-template#145] opened 2023-06-30 13:49 UTC
Hi i've update my pfsense to 2.7 and i've this message :
Notifications in this message: 1

15:43:39 PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 936, Message: Uncaught TypeError: count(): Argument https://github.com/rbicelli/pfsense-zabbix-template/issues/1 ($value) must be of type Countable|array, null given in /root/scripts/pfsense_zbx.php:936
Stack trace:
#0 /root/scripts/pfsense_zbx.php(982): pfz_dhcp_get('failover')
https://github.com/rbicelli/pfsense-zabbix-template/issues/1 /root/scripts/pfsense_zbx.php(995): pfz_dhcp_check_failover()
https://github.com/rbicelli/pfsense-zabbix-template/issues/2 /root/scripts/pfsense_zbx.php(1257): pfz_dhcp('failover', NULL)
https://github.com/rbicelli/pfsense-zabbix-template/issues/3 {main}
thrown

**Comment by Yarli** [comment] 2023-06-30 17:59
This is a duplicate of https://github.com/rbicelli/pfsense-zabbix-template/issues/135
however, the fix is simply to redownload the pfsense_zbx.php file from here and replace the one you currently have.
Ignore the version comment at hte top of the code. I don;t think it's been updated for a while.

I had this same problem today, and just copied the raw code and replaced my existing content of the pfsense_zbx.php file and it fixed my problem.

**Comment by jcattan** [comment] 2023-07-03 17:18
yes it 's works fine 
thanks

**Closed** 2024-01-20 15:12 UTC
