### ISSUE TITLE
Duplicate Triggers in Gateway Discovery Template

### ISSUE THREAD

**Issue by GuillaumeHullin** [rbicelli/pfsense-zabbix-template#156] opened 2024-01-01 12:42 UTC
The trigger prototypes in the 'Template pfSense Active' (Zabbix 6) for gateway discovery appear to be duplicated. Each pair of triggers has slightly different expressions, primarily differing by using the last value or the 3th last in the second trigger of each pair. The affected triggers are:
- **Gateway {#GATEWAY} is down**
- **Gateway {#GATEWAY} is forced down**
- **High Delay on gateway {#GATEWAY}**
- **High packet Loss on {#GATEWAY}**
- **Packet Loss on {#GATEWAY}**

1. Is this duplication intentional for some functional reason?
2. If not, should one of each pair of triggers be removed to prevent redundancy? (I can do the pull request)

**Comment by rbicelli** [comment] 2024-01-02 15:24
Sorry but don't understand your concerns:

- Gateway {#GATEWAY} is down: gateway is monitored in pfsense and monitoring is reporting that gateway is down
- Gateway {#GATEWAY} is forced down: gateway is marked down by the pfsense administrator. This raises a low-importance trigger, since is probably intentional
- High Delay on gateway {#GATEWAY}: lag is not packet loss
- High packet Loss on {#GATEWAY}: packet loss is above threshold, so critical trigger is fired
- Packet Loss on {#GATEWAY}: packet loss is under threshold, so warning trigger is fired

If you are interested only in some of that trigger, the right thing to do is disable the trigger on your pfsense host/at template level.

**Comment by GuillaumeHullin** [comment] 2024-01-02 15:54
No, the issue is that the triggers are duplicated in the template:

Here is an example for `High Delay on gateway {#GATEWAY}`. See the following [line](https://github.com/rbicelli/pfsense-zabbix-template/blob/3b364dbd32ed78fb0380d8c41f00cc353c2e56ea/zabbix6/pfsense_active.yaml#L850C1-L860C1) 

```yaml
                - uuid: fca46e537f144ea49eca155570f8da4d
                  expression: 'last(/Template pfSense Active/pfsense.value[gw_value,{#GATEWAY},status])=2'
                  name: 'High Delay on gateway {#GATEWAY}'
                  priority: WARNING
                  description: 'Gateway is lagging'
                - uuid: faaa981f96444c90accf769c5d1949a7
                  expression: 'last(/Template pfSense Active/pfsense.value[gw_value,{#GATEWAY},status],#3)=2'
                  name: 'High Delay on gateway {#GATEWAY}'
                  priority: WARNING
                  description: 'Gateway is lagging'
```

There are two triggers for the same thing... only one is the using the last value and the other the 3rd last.

**Comment by rbicelli** [comment] 2024-01-02 19:00
ok, there's something wrong because in my current template the only expression I have is (for example) :

```
- uuid: faaa981f96444c90accf769c5d1949a7
  expression: 'avg(/Template pfSense Active/pfsense.value[gw_value,{#GATEWAY},status],#3)=2'
  name: 'High Delay on gateway {#GATEWAY}'
  priority: WARNING
  description: 'Gateway is lagging'
```

So it could be a previous pull request gone sideways...

**Comment by GuillaumeHullin** [comment] 2024-01-02 19:12
Alright. well it's a different trigger even cause the one in the repo is using last() and you are using avg(). Avg() makes more sense IMO.

**Comment by aalmond-cb** [comment] 2024-04-16 22:10
As @GuillaumeHullin mentioned, there are duplicate triggers in the that exist in the current master template
[https://github.com/rbicelli/pfsense-zabbix-template/blob/master/zabbix6/pfsense_active.yaml]

You can see the duplicate at lines 851 and 856.

**Comment by rbicelli** [comment] 2024-04-27 14:02
Fixed with updated template.
The issue is raised because I was too lax accepting PRs. Will be more careful in the future.

**Closed by rbicelli** 2024-04-27 14:02 UTC
