### ISSUE TITLE
Special characters not supported on log file

### ISSUE THREAD

**Issue by perlporter** [rbicelli/pfsense-zabbix-template#115] opened 2022-03-29 19:37 UTC
Hi
even though I know it is not yet supported in version 2.6.0, I would like to report the messages I get in the zabbix agent log.
I am using the latest version.
however, the other information is working correctly

Congratulations for your work!

<img width="1440" alt="Screen Shot 2022-03-29 at 16 31 13" src="https://user-images.githubusercontent.com/4180994/160693098-e2879988-7d52-4dee-8482-c2b8f21ce877.png">

**Comment by rbicelli** [comment] 2023-02-26 16:01
Hello, sorry for the late response. This is caused by special chars in item keys. "1+[error]" contain chars that are reserved to Zabbix. So I need to apply a character substitution.

**Comment by rbicelli** [comment] 2023-02-26 16:39
Checked current source and special char substitution is in place.
Closing.

**Closed by rbicelli** 2023-02-26 16:39 UTC
